[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.ocaml]
command = "ocp-indent"
options = [ "--inplace" ]
includes = ["*.ml", "*.mli"]

# [formatter.python]
# command = "black"
# includes = ["*.py"]
# excludes = ["vendor/"]
