name: CI

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**/*'
      - '.readthedocs.yaml'
  push:
    paths-ignore:
      - '**/*.md'
      - 'docs/**/*'
      - '.readthedocs.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/cachix-action@v10
        with:
          name: tezos-checker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build dependencies
        run: nix-shell --run ':'
      - name: Check formatting
        run: nix-shell --run 'make indent && if [ -n "$(git status --porcelain)" ]; then echo "Some files require formatting, run \"make indent\"."; exit 1; fi'
      - name: Build and test
        run: nix-build -A michelson --arg doCheck true
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v13
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: cachix/cachix-action@v10
        with:
          name: tezos-checker
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build dependencies
        run: nix-shell --run ':'
      - name: Build checker with e2eTestsHack
        run: nix-build -A michelson --arg doCheck false --arg e2eTestsHack true --out-link ./checker-e2eTestsHack
      - name: Run e2e tests
        run: nix-shell --run "CHECKER_DIR=$PWD/checker-e2eTestsHack python e2e/main.py"
